name: CI
on: push

jobs:
  build_container:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages
        run: npm install

      - name: Install Lazydocs
        run: pip install lazydocs

      - name: Moving build to artifacts directory
        run: sh ./generate-docs.sh

      - name: Pushes File
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: './docs/api-docs/mlfoundry.py.md'
          destination_repo: 'sanwal-truefoundry/MLFoundry-Clone'
          user_email: 'sanwal@truefoundry.com'
          user_name: 'sanwal-truefoundry'
          commit_message: 'Commiting the .md file' 