name: CI
on: 
  push:
      branches:
        - main
        - script-run

jobs:
  build_container:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Lazydocs
        run: pip install "lazydocs>=0.4.8,<1.0.0"
      
      - name: Checkout helm-charts
        uses: actions/checkout@v2
        with:
          repository: sanwal-truefoundry/Testing-.md-collaboration
          ref: 'updating-md'
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: docs

      - name: Moving build to artifacts directory
        run: sh ./generate-docs.sh
      
      - name: Pushing file
        run: |
          cd docs
          git config user.name github-action
          git add .
          git commit -m "[CI] Update .md files"
          git push