name: CI
on: push

jobs:
  build_container:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: npm install

      - name: Install Lazydocs
        run: pip install lazydocs

      - name: Moving build to artifacts directory
        run: sh ./generate-docs.sh