name: CI
on: 
  push:
      branches:
        - main
        - script-run

jobs:
  build_container:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install -E db
      
      - name: Checkout helm-charts
        uses: actions/checkout@v2
        with:
          repository: sanwal-truefoundry/Testing-.md-collaboration
          ref: 'updating-md'
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: docs

      - name: Moving build to artifacts directory
        run: poetry run sh ./generate-docs.sh
      
      - name: Pushing file
        run: |
          cd docs
          git config user.name github-action
          git add .
          git commit -m "[CI] Update .md files"
          git push